### ISSUE TITLE
Overlapping text nodes

### ISSUE THREAD

**Issue by DanielHHowell** [vasturiano/3d-force-graph#105]
When using the text as nodes default source code, seem to randomly obtain certain nodes that are occupying the exact same 3d position and thus overlap. Tried changing the force charge to very high values <-1000 but it only changed the distance between the nodes that weren't having problems. Any ideas?

**Comment by vasturiano** [comment]
@DanielHHowell to prevent node overlap, you can add a collision force that keeps them apart.

Here's an example that uses detects collisions between nodes:
https://github.com/vasturiano/3d-force-graph/blob/master/example/collision-detection/index.html#L35

And here's another example, used to separate nodes in a tree:
https://bl.ocks.org/vasturiano/cb1a9862f2235082c9c3a21ac8457196

**Comment by DanielHHowell** [comment]
Thanks so much. Can't seem to get it work using either of those two examples with the 'text-as-nodes' variation: 

  <script>
    const Graph = ForceGraph3D()
      (document.getElementById('3d-graph'))
        .jsonUrl('network.json')
        .nodeAutoColorBy('group')
        .nodeThreeObject(node => {
          const sprite = new SpriteText(node.id);
          sprite.color = node.color;
          sprite.textHeight = 8;
          return sprite;
        });


    Graph.d3Force('charge').strength(-150);
  </script>

Any advice for using it here?

**Comment by vasturiano** [comment]
You should add an additional force to the system: [forceCollide](https://github.com/vasturiano/d3-force-3d#forceCollide).

Make sure to import `d3-force-3d` (and `d3-octree`) into your application, f.i.:
```
  <script src="//unpkg.com/d3-octree"></script>
  <script src="//unpkg.com/d3-force-3d"></script>
```

And then add the force by doing:
```
.d3Force('collide', d3.forceCollide(<radius>)
```

This will prevent nodes from overlapping within a certain spherical radius.

Additionally, it may be more appropriate to use a bounding box collision force instead of radial, because text nodes are generally rectangular. In that case you could use this force instead:
[d3-bboxCollide](https://github.com/emeeks/d3-bboxCollide).

**Comment by DanielHHowell** [comment]
Amazing, got it perfect. Thank you!
