### ISSUE TITLE
Add class to node

### ISSUE THREAD

**Issue by estebanpdl** [vasturiano/3d-force-graph#125]
Is it possible to add a html class to each node? I would like to custom each node using css. For example, add a border shadow. Or can I custom nodes in an specific `3d-force-graph` method?

**Comment by vasturiano** [comment]
@estebanpdl you can't use traditional classes (and css) because the nodes in the graph are rendered using `WebGL`, therefore they're not separate stylable entities in the DOM. However, you can design the nodes in whichever way you wish, using the `.nodeThreeObject(...)` method, but you'll have to write some `ThreeJS` code for that.
Here's an example: https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/
And the source: https://github.com/vasturiano/3d-force-graph/blob/master/example/custom-node-geometry/index.html

**Comment by estebanpdl** [comment]
Thanks, @vasturiano I was following exactly that example. Thanks
