### ISSUE TITLE
Text as node interactions

### ISSUE THREAD

**Issue by SimonDeDeyne** [vasturiano/3d-force-graph#127]
Is there any way of adding node interactions when the nodes are text sprites?
I'm thinking of highlighting the text, direct neighbors and edges between them...

Thanks!

**Comment by vasturiano** [comment]
@SimonDeDeyne all the node interaction methods should still work, even with custom Three object definitions, such as using sprites.
Then you can add highlighting functionality based on your logic using those methods, like in this example:
https://vasturiano.github.io/3d-force-graph/example/highlight/

**Comment by vasturiano** [comment]
@SimonDeDeyne you're right, it appears these methods don't work well with Sprite object types.
The culprit seems to be that Three's [raycaster](https://threejs.org/docs/#api/en/core/Raycaster) has difficulty detecting Sprite types, but works fine for meshes and particles.
This requires a deeper look. For now what I'd suggest to group your sprite with an invisible mesh (like a sphere) so it can be used as a trap for the raycaster detection.
Let me know if that works out.

**Comment by mingtao13595** [comment]
> @vasturiano
> Thanks for the tip, I tried but it seems there's something missing. Could it be because we're using sprites instead of nodes? The simple example with just nodes works..
> 
> ```
> <html>
>     <head>
>         <script src="//unpkg.com/three"></script>
>         <script src="//unpkg.com/3d-force-graph"></script>
>         <script src="//unpkg.com/three-spritetext"></script>
>     </head>
> <html>
> <body>
> <div id="3d-graph"></div>
> </body>
> <script>
> 
> const Graph = ForceGraph3D()
>   (document.getElementById('3d-graph'))
>     .jsonUrl('/networks/miserables.json')
>     .nodeAutoColorBy('group')
>     .nodeThreeObject(
>       node => {
>         const sprite = new SpriteText(node.id);
>         sprite.color = node.color;
>         sprite.textHeight = 7;
>         sprite.fontFace = 'Cabin';
>         sprite.fontSize = 99;
>         return sprite;
>     })
>    .onNodeHover(node => {
>       console.log('node: ',node);
>     });
> </script>
> </html>
> ```

Could the node information displayed by 
.onNodeHover(node => {
      console.log('node: ',node);
in your case?
Or just cannot work as you mentioned firstly?
Thank you in advance.
