### ISSUE TITLE
Click to focus is flaky with Chrome

### ISSUE THREAD

**Issue by GaborSzalai** [vasturiano/3d-force-graph#135]
I'm experiencing some issues with the click to focus example when opening in Chrome. If I just open it on a new tab, clicking on the node results in a slight movement of all the nodes, but nothing else happens. I tried moving the nodes, clicking on different ones, orbiting the view etc. but the results are the same. However, if i open the page in a new window, suddenly it all works with click to focus happening.

I also used the example code locally and saw the same thing. Strangely, in my local instance, the issue is often resolved by resizing the screen, though that seems quite random (sometimes it works, sometimes not). Opening in a new window, however, seems to resolve this 100%.

I also tried with Edge browser and that just seems to work fine.

**Comment by vasturiano** [comment]
@GaborSzalai thanks for reaching out. Are you seeing that behaviour on this page?
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

From your description, it seems that you're engaging a node drag instead of just clicking on it. Does it also happen if you click without moving the mouse pointer in the meantime?
If so, I wonder if it's a particular version of Chrome (I can't reproduce on latest). Which version are you using?

**Comment by GaborSzalai** [comment]
That's the page yes and I am on Version 69.0.3497.100. 
I think your hunch about node drag was spot on - I switched dragging off in my local instance by using `enableNodeDrag(false)` and now click to focus works in a stable manner.

**Comment by rafaelbusetti** [comment]
In the link the same problem occurs (
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/)

Soon after doing the drag, quickly click on some node, the click on the node is not fired. (I tested it on Chrome)
