### ISSUE TITLE
Always display node objects over links in a simple way?

### ISSUE THREAD

**Issue by stdob** [vasturiano/3d-force-graph#149]
Hi!

Thanks for the great library!

Is it possible to always display node objects (sprites) over links in a simple way? 

Because avatars of nodes that have many links become invisible behind the links:

![graph](https://user-images.githubusercontent.com/15095605/49602868-a008a100-f99a-11e8-9abe-fee4f8bbfe9e.png)

**Comment by vasturiano** [comment]
Hi @stdob, thanks for reaching out. Normally objects that are closer to the camera will display on top of objects that are further away. I don't know of an easy way to change that. Also not sure if it would be intuitive visually, and it would probably affect the sense of perspective.
What you could try is adjust the opacity of the links so that the overlay is less jarring on the objets that are behind.

**Comment by stdob** [comment]
Hi @vasturiano, thank you for your answer!

I see two options:

1) Render the scene with links layer first, then the scene with nodes layer:

> renderer.clear()
> camera.layers = 1 // For example, links are in the layer N1.
> renderer.render(scene, camera)
> renderer.clearDepth()
> camera.layers = 2 // And nodes are in the layer N2.
> renderer.render(scene, camera)
>renderer.clearDepth()

2) Consider the node size in drawing links, i.e. start drawing a link not from the center of the node, but from its border.
