### ISSUE TITLE
onEngineTick

### ISSUE THREAD

**Issue by nitrosx** [vasturiano/3d-force-graph#172]
The function associated with onEngineTick gets called only twice (the first and last tick) even if I have set a total of 21 ticks.

Here is a simplified version of the code:

const graphWarmupTicks = 20;
const graphCooldownTicks = 1;

var graph = ForceGraph3D()
  . dagMode('radialout')
  .onEngineStop(stopForceEngine)
  .onEngineTick(updateForceEngineStatus)
  .warmupTicks(graphWarmupTicks)
  .cooldownTicks(graphCooldownTicks);

stopForceEngine gets called when the last tick has been reached, while updateForceEngineStatus is called on the first and last tick.

Thanks

**Comment by vasturiano** [comment]
@nitrosx thanks for reaching out. That behaviour is actually intended. `onEngineTick()` is not supposed to be called on `warmupTicks`, because those are performed before the animation engine starts running (which is what is tracked by `onEngineTick`). So in your case you effectively only have one tick, specified by `.cooldownTicks(1)`.

**Comment by sheehan** [comment]
@vasturiano is there any way to hook into the warmup ticks? I'd like to add some logic there, but I don't want to animate the initial layout.

**Comment by vasturiano** [comment]
@sheehan not really, because the warmup phase of the simulation is ran as a batch using d3-force's [tick iterations](https://github.com/vasturiano/d3-force-3d#simulation_tick) loop. So the process is opaque, you'll only be able to hook in some additional functionality once the rendering phase begins.

Is your logic not suitable to be added to the first engine tick when the cooldown phase begins?

**Comment by sheehan** [comment]
Thanks @vasturiano. I was trying to constrain some nodes inside a sphere, but was able to get it working using a custom force.

**Comment by vasturiano** [comment]
@sheehan ok great. It actually makes more sense to do that using a force than to manipulate the nodes coordinates directly.
There is for example [d3-force-limit](https://github.com/vasturiano/d3-force-limit) which can be used to restrict nodes positions.

**Comment by joekroese** [comment]
@sheehan are you able to share any code for constraining nodes with a custom force? I'm looking to do the same thing and it would save me some time to see your implementation 😇
