### ISSUE TITLE
Add options to always display labels for nodes and links

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [vasturiano/3d-force-graph#179]
Currently, text labels are displayed only when pointing/hovering to a specific node or link.

Please add an option to always display text labels for all nodes and an option to always display text labels for all links.

I know about workarounds for [nodes](https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html) and [links](https://github.com/vasturiano/3d-force-graph/blob/master/example/text-links/index.html) using `three-spritetext`. But it would be great to do without additional packages.

**Comment by vasturiano** [comment]
@FluorescentHallucinogen thanks for your suggestion. I do understand you point of view. The reason why the addition of node/link labels is configured using external methods is that there is just too much variance on how users want that to look like. Anything from font size, font type, color, length, position, orientation, ellipsis, etc leads to possible variations of those labels. And every use case tends to demand a different configuration. That's why I found that having that configuration as an external method is the most generic approach that imposes less restrictions on the consumer.

**Comment by FluorescentHallucinogen** [comment]
What if I (and probably some other users) don't need any customization? Users who need advanced configuration can use external methods.

**Comment by gdswapnil11** [comment]
> @FluorescentHallucinogen thanks for your suggestion. I do understand you point of view. The reason why the addition of node/link labels is configured using external methods is that there is just too much variance on how users want that to look like. Anything from font size, font type, color, length, position, orientation, ellipsis, etc leads to possible variations of those labels. And every use case tends to demand a different configuration. That's why I found that having that configuration as an external method is the most generic approach that imposes less restrictions on the consumer.

@vasturiano can u plz provide us sample code for that, how add label on node using three-spritetext

**Comment by FluorescentHallucinogen** [comment]
@gdswapnil11 See the links in the first message.
