### ISSUE TITLE
Images as nodes with transparent background shown as white and covers link

### ISSUE THREAD

**Issue by Hyssopi** [vasturiano/3d-force-graph#181]
Hello.

I have a bunch of images with transparent background:
![image](https://user-images.githubusercontent.com/43843070/53625273-7afd8600-3bb7-11e9-9db8-83f78bc58fbb.png)

But when I put them in as nodes, the transparent background becomes white and blocks the links.

![image](https://user-images.githubusercontent.com/43843070/53625184-438ed980-3bb7-11e9-8194-e460e0f427ea.png)

Putting in `alphaTest: 0.5` in SpriteMaterial fixes the issue but the sprite resolution becomes blocky and unrecognizable.

Also for some reason, the length and width of the image become square-y.
This:
![image](https://user-images.githubusercontent.com/43843070/53625539-3faf8700-3bb8-11e9-9dd9-c6c9fba488bf.png)
becomes compressed as screenshot shown above.

Here is my code:
https://github.com/Hyssopi/Pokemon-Graph-2
and a working GitHub Pages:
https://hyssopi.github.io/Pokemon-Graph-2/

**Comment by vasturiano** [comment]
@Hyssopi I think this is more of a `ThreeJS` question than a `3d-force-graph` question. It's all in the way that you setup your image sprites and there's probably a way to configure it to not render the transparent background. Same for the aspect ratio of the sprite, you should probably scale the sprite to the dimensions that you wish: https://github.com/Hyssopi/Pokemon-Graph-2/blob/master/src/main.js#L91

Another thing to mention is that you'll probably want the encompassing sphere object to be fully transparent, so with `opacity: 0` instead of `opacity: 1`: https://github.com/Hyssopi/Pokemon-Graph-2/blob/master/src/main.js#L83
