### ISSUE TITLE
onNodeClick(...) not triggering when Graph/Camera has recently moved or still moving

### ISSUE THREAD

**Issue by Hyssopi** [vasturiano/3d-force-graph#182]
Here is my code:
https://github.com/Hyssopi/Pokemon-Graph-3
and a working GitHub Pages:
https://hyssopi.github.io/Pokemon-Graph-3/

Can be easily reproduced. Left clicking on a node is supposed to highlight the connecting links. But notice it does not work when moving the camera or when it is recently moved. Wait until camera is at full rest then click, then it works.

**Comment by Alexithemia** [comment]
I seem to be having this same issue, the links above don't work, but after the camera is moved is any way, left and right click functions don't work for a short time, around 2-3 seconds.

You can see it on your examples, 
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/
and
https://vasturiano.github.io/3d-force-graph/example/expandable-nodes/

**Comment by vasturiano** [comment]
@Hyssopi @Alexithemia are you per chance using a trackpad and a 3-finger drag motion to move the camera?

By design, the node hover/click interactions are disabled while the camera is being moved. That's intentional as it was too confusing if the two interaction types were firing simultaneously.

What may be happening here is that some pointer devices, like the OSX trackpad lock the click+drag motion for a bit of time after releasing. This is so you have dragging continuity even if you momentarily let go of it. During this extended time the browser actually thinks the user is still dragging, and therefore the other interactions remain disabled briefly. It's just a coincidence that it roughly matches the inertia of the camera motion slow-down.

An easy way to test this is to perform the rotation using a regular click+drag interaction and observe if the issue still persists.

A bit more background here: https://apple.stackexchange.com/questions/243151/how-to-speed-up-three-finger-drag-delay-on-release
