### ISSUE TITLE
linkColor(...) not triggering when a variable changed

### ISSUE THREAD

**Issue by Hyssopi** [vasturiano/3d-force-graph#183]
Forgive me for being new and asking this newbie question but here is my assumption on how this works (given how the examples worked):
```
.linkDirectionalParticles(link => link === highlightLink ? 4 : 0)
```
When the variable `highlightLink` has changed somewhere, then `linkDirectionalParticles` will automatically know when to call itself and do `link === highlightLink ? 4 : 0`.

Given this assumption, I assume it is something similar to VueJS computed (automatically knows when a variable inside has changed and will call itself).

Here is my code:
https://github.com/Hyssopi/Pokemon-Graph-3
and a working GitHub Pages:
https://hyssopi.github.io/Pokemon-Graph-3/

Notice the link colors are black when you load it.

However, the code for linkColor is:
```
.linkColor(link =>
  {
    let {nodes} = graph.graphData();
    if (nodes.indexOf(link.target) === -1)
    {
      return '#000000';
    }
    else
    {
      return nodes[nodes.indexOf(link.target)].color;
    }
  })
```

Once you click on any node, the `onNodeClick(...)` calls `graph.nodeRelSize(4)` which I guess will recall `linkColor(...)` and the link colors are properly set.

Shouldn't `linkColor(...)` automatically be recalled after the graph has loaded the nodes?

**Comment by vasturiano** [comment]
@Hyssopi thanks for reaching out. The `linkColor` function only gets called (per link) when any of the graph properties are updated (by invoking one of the update methods). Basically the module has no way of knowing that at a certain point your `linkColor` function will return a different value (because it is coupled with state that lives outside of the graph object). And calling it at every graph tick to verify the value would impose too large of a performance penalty.
What I would suggest is that you force a graph update whenever your external state changes (by calling f.e. `.nodeRelSize(4)`). That will trigger the `.linkColor()` function to be re-ran for every link.

**Comment by ddooley** [comment]
I'm just double checking here - Is there any way to send a message to the rendering engine to tweak the state of its one edge or node?  I'm using .forceEngine('d3') .  At moment I am changing a node color on click, and then triggering Graph.nodeRelSize(4) ; but this creating quite a delay when I can see though that the rendering engine has no problem zooming, panning, etc. otherwise. I.e. seems like it could make the change in a millisecond.

**Comment by ddooley** [comment]
I just found one direct-to-rendering engine solution which applies if one is adding sprites or custom-defining nodes.  For a node that one wants to highlight, keep a reference to the THREE mesh or sprite etc.

function init() {
   return ForceGraph3D()(document.getElementById('3d-graph'))
    .forceEngine('d3')  
    .nodeThreeObject(node => render_node(node))
     ...

function render_node(node) {
  // Displays semi-sphere, then overlays with label text
  var group = new THREE.Group();
    var geometry = new THREE.SphereGeometry(nodeRadius, 8, 6, 0, Math.PI);
    var material = new THREE.MeshBasicMaterial( { color: node.color } );
    var circle = new THREE.Mesh( geometry, material );
    circle.position.set( 0, 0, 0 );
    group.add( circle );
    **node.marker = circle;**

then, whatever event changes the color of the rendered object, set color of the marker, and this change is visible right away. No .nodeRelSize(4) necessary!

    node.marker.material.color.setHex(0xFF0000); // talk straight to rendering engine!
