### ISSUE TITLE
Issues with 2d layout

### ISSUE THREAD

**Issue by zzggyy1** [vasturiano/3d-force-graph#197]
Hello,

First off I have to congratulate you on this awesome graph library. 
I am encountering an issue when I am switching from 3d to 2d layout if I set Graph.d3Force('collide', d3.forceCollide(Graph.nodeRelSize())) initially in the 3d layout (I tried removing this part of the code and then all works fine). How can I solve this issue?

Thank you in advance!
Guangyan

**Comment by vasturiano** [comment]
@zzggyy1 thanks for reaching out.

Is this the error that you're getting? `r.quadtree is not a function`

If so, you need to import [d3-quadtree](https://github.com/d3/d3-quadtree), just like you're doing for [d3-octree](https://github.com/vasturiano/d3-octree). Because collision forces in 2d use a quadtree for optimization (and a binary-tree in 1d, and an octree in 3d).

**Comment by zzggyy1** [comment]
Thank you for your help @vasturiano, it fixed the problem!
