### ISSUE TITLE
switch from 2D to 3D layout

### ISSUE THREAD

**Issue by zzggyy1** [vasturiano/3d-force-graph#201]
Hello All,

When I switch from 2D layout to 3D layout the graph largely remains flat (2D). I have tried modifying the nodes xyz positions (x, vx, y, vy, z, vz) to 0 in an attempt to reset the positions but it didn't work as expected. Is there something else I can do to reinitialize the node positions?

Thank you!

**Comment by vasturiano** [comment]
@zzggyy1 the misalignment is most likely due to the residiual information on the `z` dimension. Setting the `z` attributes to `0` should reset it, if you do it after the layout is changed to 2d.

You can also re-pass a fresh dataset (that doesn't have any `x, y, z` attributes memory) by calling `graphData(...)`, that will ensure the the node positions reset and is probably the cleanest approach.
