### ISSUE TITLE
remove "gravity" in 3D graph for displaying graph where all nodes are connected

### ISSUE THREAD

**Issue by noahtren** [vasturiano/3d-force-graph#209]
Thanks for this great tool!

I have a question about the physics engine. There seems to be a "gravitational" force in addition to the attractions between connected nodes and repulsive force between all nodes. My understanding is that this exists so that all clusters of nodes exist within a sphere.

I am trying to create a visualization where all nodes are connected, and the gravitational force is resulting in behavior I wasn't anticipating. Specifically, in this visualization of a simple autoencoder neural network, the ends seem to bend towards each other where I would imagine the layers should spread out from each other horizontally.

Is there any way to avoid this behavior?
![](https://cdn.discordapp.com/attachments/571130107339472906/594661126365773845/unknown.png)

**Comment by vasturiano** [comment]
@noahtren thanks for getting in touch. The only other force included by default is [forceCenter](https://github.com/vasturiano/d3-force-3d#forceCenter). This force's intention is to prevent the nodes from drifting out of the canvas, by translating them so that the center of gravity of all the nodes combined remains at the canvas center.

This force can be easily disabled by doing:
```
myGraph.d3Force('center', null)
```

**Comment by noahtren** [comment]
Thanks so much for the help. This is exactly what I was looking for.
