### ISSUE TITLE
How to set up Camera？

### ISSUE THREAD

**Issue by lettywiterock** [vasturiano/3d-force-graph#21]
I used THREE -->  new THREE.PerspectiveCamera()
in  nodeThreeObject()
-->Error

How to set up Camera？
HELP ME (っ °Д °;)っ

**Comment by vasturiano** [comment]
@lettywiterock `nodeThreeObject` should receive a three [Object3d](https://threejs.org/docs/#api/core/Object3D). No need to supply a camera, that's handled by the framework already. Any instance of a [Mesh](https://threejs.org/docs/#api/objects/Mesh) should work. Something like:
```
Graph.nodeThreeObject(d => new THREE.Mesh(
          new THREE.BoxGeometry(Math.cbrt(d.value), Math.cbrt(d.value), Math.cbrt(d.value)),
          new THREE.MeshLambertMaterial({ color: 0xFF0000 })
));
```

Here's a working demo:
https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/

**Comment by AmbroiseCouissin** [comment]
What if we want to specify the orbiting? For example, having only horizontal orbiting allowed?

**Comment by vasturiano** [comment]
@AmbroiseCouissin can you give an example of what orbiting is? 
Do you mean something like this:
https://bl.ocks.org/vasturiano/29550a65f206d513264e95c8ce2884ab

**Comment by AmbroiseCouissin** [comment]
@vasturiano Sorry, i meant this: https://threejs.org/docs/#examples/controls/OrbitControls

**Comment by vasturiano** [comment]
Ah I see. Well, the component uses [trackball controls](https://threejs.org/examples/misc_controls_trackball.html) instead of orbit controls for controlling the camera. The main difference is that trackball controls don't enforce a strict 'up' orientation, which seemed more appropriate since the force-generated graphs don't have a particular meaning associated to any direction.
