### ISSUE TITLE
Is it possible to change the label text while the label is being displayed?

### ISSUE THREAD

**Issue by ProductiveRage** [vasturiano/3d-force-graph#220]
Say that I have point data (x, y, z) for the data that I want to display but I don't pre-load all of the text labels for each point\*, is there a good way to wait until the User hovers over a point and to then retrieve the label text and update the display (where the label shows a generic "Loading.." message until the data arrives)?

\* (Because I've got 10s of 1,000s of points and the labels can be quite long - so downloading _all_ of that content in one go can be too expensive)

What I've tried so far is to initialise all points with a "Loading.." label value and to then use onNodeHover to initiate the data retrieval - the problem is then updating the graph with the new label. I've tried calling graphData again to redraw with the new content and this changes the label text but it also adjusts the view of the graph slightly, even though none of the point positions have changed.

In my use case, I don't think that I need to support dynamically adding and removing nodes from the graph and so I'm calling cooldownTicks(0) (inspired by issue #170) after the graph is first rendered so that it _doesn't_ change its position when I call graphData to update label content.

I wondered if there was a better way to achieve this, though. If I _do_ want to support adding or removing nodes after the first render then cooldownTicks(0) may come back to bite me in the future. Any guidance much appreciated!

**Comment by vasturiano** [comment]
@ProductiveRage thanks for reaching out.
Using `cooldownTicks(0)` is what I would do in your case. Essentially you're disabling the force engine re-heating on those hover interactions.

As for having this co-exist with other interactions in which you may want the re-heat (like node addition/removal), it's just a matter of manipulating the `cooldownTicks` value per interaction type, so that you set it to `0` before updating labels, but to a positive value before adding/removing nodes.

**Comment by ProductiveRage** [comment]
Thanks for getting back to me so quickly!

I will consider the calling of cooldownTicks at the appropriate times the solution, then. Thanks again!
