### ISSUE TITLE
use lineDashedMaterial  for links not working

### ISSUE THREAD

**Issue by Reyhan96** [vasturiano/3d-force-graph#224]
i want to use dashed line instead of line for links but when i set the material using .linkMaterial it is not worked....
how can i have dashed lines for links ?

here is the code : 
`.linkMaterial(link => {
          var material = new THREE.LineDashedMaterial( {
            color: 0xffffff,
            linewidth: 1,
            scale: 1,
            dashSize: 1,
            gapSize: 0.5,
          } );
          return material;
        });`

**Comment by vasturiano** [comment]
@Reyhan96 thanks for reaching out.

The issue you're experiencing is because for `LineDashedMaterial` to function properly, you need to run `computeLineDistances()` on the `Line` object every time their position gets updated. As mentioned in the Three docs: https://threejs.org/docs/index.html#api/en/objects/Line.computeLineDistances

The lines are updated at every tick of the force layout engine, therefore you can inject this functionality using `linkPositionUpdate`, like so:
```
  .linkPositionUpdate(lineObj => { lineObj.computeLineDistances() })
```

Depending on the number of links you have in your data, this may have perceivable rendering  performance implications, since it's an expensive computational operation to run at every frame. You could potentially optimize it by debouncing or throttling it, but you'll have to write some custom code for that.
