### ISSUE TITLE
Expand graph by click

### ISSUE THREAD

**Issue by Biuni** [vasturiano/3d-force-graph#231]
I have a big hierarchical graph (a tree) and i need to expand it step by step.
When i load the graph, i want to visualize only the "root" node and by clicking it i want to open all child nodes. It's possible to make this type of visualization/navigation?

**Comment by vasturiano** [comment]
@Biuni thanks for reaching out.
Yes, that's very doable. I just created a new example with that type of functionality. 
Please check it here: https://vasturiano.github.io/3d-force-graph/example/expandable-nodes/

The red nodes represent collapsed nodes, while the yellow ones are expanded. Clicking on the node will toggle their expanded/collapsed state.
Green nodes are graph leaves and clicking on them has no effect.

Keep in mind this type of functionality is only possible if the graph is not cyclical. Otherwise you'll hit a traversal infinite loop.

Here is the [example source](https://github.com/vasturiano/3d-force-graph/blob/master/example/expandable-nodes/index.html).
