### ISSUE TITLE
Nodes move away on Click

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#232]
Not 100% sure if this is there on purpose, but every time a node is clicked or right clicked, the other nodes move away from it slightly. If you hold the click, they continually move away. Is this a bug? or is it on purpose and is there a way to stop this from happening?

It's not like they are moving away from the node you click, they just move away from center.

Appears to happen in all your examples.

I am on Windows 10, occurs in both latest versions of Chrome and Firefox.

Do I need to look into turning off the engine while they are clicked?

In my specific use case I just need the nodes to stay a minimum distance from each other and follow dagMode forces, while I use click functions to interact with the data, and have dragging capabilities.

**Comment by vasturiano** [comment]
@Alexithemia thanks for reaching out. 

The motion you're seeing is when the force simulation gets reheated. This is triggered when a drag interaction is detected on a node. This is intentional and so the layout can adjust to the new configuration set by the node drag. 
But, this is only triggered on node drag, not on single click. Could it be that you're dragging the nodes ever so slightly when clicking? This can happen easily with some pointer devices like trackpads.

**Comment by Alexithemia** [comment]
I am just using a regular mouse and it does show the hand grabbing for a moment like I was dragging, but it is just a normal click, left or right, and it is firing the onNodeClick or onNodeRight click methods.

**Comment by vasturiano** [comment]
@Alexithemia I've improved the trigger for the simulation reheat so it only activates when the mouse pointer is moved while holding the click. 
Please pull the latest version (`1.55.9`) and let me know it solves it for you.

**Comment by Alexithemia** [comment]
That works beautifully thank you. I'll be buying you a coffee or two if this gets accepted for use in my project, you write some great stuff.
