### ISSUE TITLE
Text in Links example not working when setting linkWidth >0

### ISSUE THREAD

**Issue by HansvdLaan** [vasturiano/3d-force-graph#238]
**Problem**
The Text in Links example doesn't work when we modify the link width. 

When we set linkWidth >0, the labels don't get placed in the middle of the links. Instead, they appear all over the graph. 

![image](https://user-images.githubusercontent.com/9132846/66593557-86764e00-eb97-11e9-9c48-5847db9c5981.png)

Since it seems the code shouldn't be affected by the link width, I suspect there is a bug somewhere.  What is also weird that even if we set linkWidth to 0.1, which should be rounded down to 0, we still get the same behaviour. 

I created a [codesanbox ](https://codesandbox.io/s/angry-sara-vuo4z?fontsize=14) which shows the bug.

**Comment by vasturiano** [comment]
Thanks for the report @HansvdLaan! This should now be fixed in `v1.55.11` of `3d-force-graph`.

Re: the `linkWidth`, the rounding method is up to the next decimal, so no number is rounded to `0`. Even `0.001` would round up to `0.1`. This is to prevent the default line behavior if any custom width has been set. Code here: https://github.com/vasturiano/three-forcegraph/blob/master/src/forcegraph-kapsule.js#L286

**Comment by HansvdLaan** [comment]
Thanks for the heads-up! :)
