### ISSUE TITLE
Click events, camera reset, center forces

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/3d-force-graph#241]
Had four issues/questions to run by you, didn't want to clutter up your issues with multiple.

The first two are with click functions on the graph. 
Is there any way you could provide the click event in the .onNodeClick, .onNodeRightClick, etc.?
That way it could be used to get an X and Y location of the graph container to attach a context menu or custom tooltip there? I currently have a click event listener, on the container the graph is attached to, running some code alongside the graph clicks to make this work for now.

There is an [older issue](https://github.com/vasturiano/3d-force-graph/issues/182) I commented on that I don't know if you saw, but when the camera is moved in any way, any graph clicks do not work for around 2-3 seconds, maybe waiting for the camera to settle?
You can see this in your two examples with click functionality.
https://vasturiano.github.io/3d-force-graph/example/expandable-nodes/
and
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

Third I am trying to give the ability for a user to reset the camera on the graph to the same position each time. There was [another old issue](https://github.com/vasturiano/3d-force-graph/issues/94) about this and I am having the same issue, as the camera will go to the same location but I cannot reset the rotation. I have tried multiple ways to use the Graph.camera( ) to change the rotation, with quaternions, rotation, matrix, but none of them are changing the camera. How exactly would I use Graph.camera( ) to change the rotation?

Last is there any way to flip the center force to repel all nodes and specify the strength? Trying to make a radial view mode and repel all nodes from center with them all attached to a fixed center node.

Sorry for the long issue post, I would be happy to provide you an example of this complex graph setup when I am done.

**Comment by veryspry** [comment]
I was wanting the event object passed to node/link click callbacks as well. I decided to take a pass at it and put up some pull requests to handle it - one in [3d-force-graph](https://github.com/vasturiano/3d-force-graph/pull/243) and one in [three-render-objects](https://github.com/vasturiano/three-render-objects/pull/3 ).

**Comment by vasturiano** [comment]
@veryspry thanks for creating those PRs, they're useful additions. I'll have a closer look and get it merged when I have a moment. 👍 

@Alexithemia re your other questions:

> There is an older issue I commented on that I don't know if you saw, but when the camera is moved in any way, any graph clicks do not work for around 2-3 seconds, maybe waiting for the camera to settle?
You can see this in your two examples with click functionality.
https://vasturiano.github.io/3d-force-graph/example/expandable-nodes/
and
https://vasturiano.github.io/3d-force-graph/example/click-to-focus/

I answered it in the issue. It's possibly related to trackpad drag movements. Could you please try with a regular mouse and see if the issue persists?

> Third I am trying to give the ability for a user to reset the camera on the graph to the same position each time. There was another old issue about this and I am having the same issue, as the camera will go to the same location but I cannot reset the rotation. I have tried multiple ways to use the Graph.camera( ) to change the rotation, with quaternions, rotation, matrix, but none of them are changing the camera. How exactly would I use Graph.camera( ) to change the rotation?

This is not really `3d-force-graph` specific but more on how to perform camera orientation changes. It's not trivial. You'll probably need to use transformation matrixes to ensure consistent orientation. Alternatively, you could switch to `orbit` controls that mantains the "up" orientation throughout.

> Last is there any way to flip the center force to repel all nodes and specify the strength? Trying to make a radial view mode and repel all nodes from center with them all attached to a fixed center node.

I think the center force is not what you want for this. That force basically just translates the nodes positions so that the graph center of gravity is at the center of the canvas. 
If this were 2d I'd suggest to use [d3.forceAttract](https://github.com/ericsoco/d3-force-attract) and set a negative charge to (0, 0). But this force plugin needs to be converted to 3 dimensions to function properly.
Perhaps you could replicate that behavior with the [forceX, forceY and forceZ](https://github.com/vasturiano/d3-force-3d#forceZ) variants.

You can also browse more available force types in the [d3-force-registry](https://github.com/vasturiano/d3-force-registry).

**Comment by Alexithemia** [comment]
For the click after camera change issue, I am using a regular mouse when I experience this, but switching to orbit controls as you recommended in the 2nd issue fixes this problem, as it seems the camera stops as soon as you let go of the mouse (i.e. you can't use the mouse to fling the graph in circles).

Still looking into the forces I'll get back to you on what works. Thanks
