### ISSUE TITLE
ngraph VS default force layout

### ISSUE THREAD

**Issue by aabversteeg** [vasturiano/3d-force-graph#30]
Hi there,

Thank you very much for this great library. Unfortunately, I ran into a problem.

The ngraph and the default d3 force layout algorithms differ; the former resets the layout whereas the latter does not when a node or edge is added/removed.

As a consequence, I cannot use the ngraph algorithm, even though it gives better results.

For instance, see an adjusted version of the "dynamic example": [https://jsfiddle.net/97ov1cz6/5/](https://jsfiddle.net/97ov1cz6/5/)

**Comment by vasturiano** [comment]
@aabversteeg I'd recommend using the d3 engine if you'll be doing dynamic graph updates.

The two engines have different behaviours because they're calibrated differently. But the d3 engine can actually be configured so that it behaves similar to `ngraph`. You can do this using the methods `d3AlphaDecay`, `d3VelocityDecay` and  `d3Force`. 

`ngraph` by default has a more "tense" [configuration](https://github.com/anvaka/ngraph.physics.simulator/blob/master/index.js) than the d3 engine. If that's what you're seeking, you can increase the node's repelling charge, and decrease the velocityDecay (drag). Something like this will get you a little closer:
```
myGraph.d3VelocityDecay(0.2);
myGraph.d3Force('charge').strength(-100);
```
