### ISSUE TITLE
Control the light

### ISSUE THREAD

**Issue by MaksZhukov** [vasturiano/3d-force-graph#305]
In react I can control the initial light in the scene in componentDidMount, but it works when I use setTimeout because some children aren't on the scene at componentDidMount moment.

**Comment by vasturiano** [comment]
@MaksZhukov that's correct. The rendering is done asynchronously, so the scene is not guaranteed to be be complete immediately after component mount.

**Comment by MaksZhukov** [comment]
@vasturiano Yes, but maybe you know another solution, because use setTimeout in didMount lifecycle is not good and setTimeout with 0 delay doesn't guarantee to have all the children in the scene

**Comment by vasturiano** [comment]
@MaksZhukov if you use the `setTimeout` in your `componentDidMount`, I believe the scene should be always fully populated by then, because it runs asynchronously without further delay.
I think this is the best, if not the only option for doing this. 

Also, it should be fine to add asynchronous operations to `componentDidMount`, that's the place that's the most appropriate for it.

**Comment by MaksZhukov** [comment]
@vasturiano but maybe if we have a prop like a callback what indicates that the scene is fully populated it would be great.
Ok, thank you

**Comment by Alexithemia** [comment]
I put a callback inside .onEngineStop() to indicate when my graph is complete. It may take longer than you are expecting to finish though, depending on how many nodes you have and how many forces are applied. This waits until all nodes finish moving according to forces.
