### ISSUE TITLE
Add particles in the link

### ISSUE THREAD

**Issue by SailinZh** [vasturiano/3d-force-graph#33]
Thank you for the fantastic library. 

I'm looking to add moving particle systems within the links like the photon animation in this video: https://www.youtube.com/watch?v=JsEm-CDj4qM. Would it be possible?

**Comment by vasturiano** [comment]
That looks beautiful @SailinZh, thanks for sharing.

To add the additional elements, I'd recommend you use the lower level [three-forcegraph](https://github.com/vasturiano/three-forcegraph) Three component instead. That will allow you to combine the new photon particles with the nodes/links generated by the force-directed engine.

You can access the current coordinates of the nodes as `x`, `y`, and `z` attributes of the objects.

You'd also need to take care of the render/scene/camera scaffolding, but there's an example here to guide you, if you need:
https://github.com/vasturiano/three-forcegraph/blob/master/example/basic/index.html

**Comment by vasturiano** [comment]
@SailinZh I add a shot at this and added the feature to have moving particles indicate the directionality of links, since it was a needed feature of the library anyway.

Working example here:
https://vasturiano.github.io/3d-force-graph/example/directional-links/

This is achieved via the new component methods: `linkDirectionalParticles`, `linkDirectionalParticleSpeed`, `linkDirectionalParticleWidth` and `linkDirectionalParticleResolution`.

Let me know if this works for you. And thanks again for suggesting it.
