### ISSUE TITLE
link attribute of json data does not takes decimal values in 3D text nodes graph.

### ISSUE THREAD

**Issue by karanaryan07** [vasturiano/3d-force-graph#338]
I was passing the graph data as props in the required format for 3D text nodes graph
[https://github.com/vasturiano/react-force-graph/blob/master/example/text-nodes/index-3d.html](url)
But it failed to render the react force graph when I am using decimal values in the "links" attribute of the graph data.

While it is working fine with the data which is used to display 3D text nodes graph 
[https://github.com/vasturiano/react-force-graph/blob/master/example/datasets/miserables.json](url)

this is the console output of the graph data which is being passed as props.

![Screenshot (953)](https://user-images.githubusercontent.com/43538207/85958491-7ca9aa80-b9b3-11ea-85fa-e97918bc7c77.png)

**Comment by vasturiano** [comment]
@karanaryan07 thanks for reaching out.

It's difficult to say where the problem lies without more details. Could you create a simple reproducible example on https://codepen.io/ so it can be debugged further.

The fractional values on your data shouldn't cause anything to break, but it really all depends on what you're using that attribute for. The module itself doesn't have awareness of that attribute until you use it for some purpose, like sizing the width of the links for example.

**Comment by Alexithemia** [comment]
What are you trying to make the links do with the value attribute?

I don't think links use a value by default. Are you trying to influence the link width or link force with it?

**Comment by Circles24** [comment]
@karanaryan07 
The problem isn't that ForceGraph3D doesn't work with floating point values rather it lies somewhere else.


Since you are passing props as graphData to ForceGraph3D,  props are read-only in react and ForceGraph3D mutates the given input object hence in this case its unable to modify the object.

What you can do is write a method which makes a deep copy of this props and instead of passing the props you can then pass the deep copy as graphData


```
const PropsDeepCopy = (graphData) => {
    const proxy = {};
    proxy.nodes = graphData.nodes.map((data) => ({
        id : data.id ,
        group : data.group
    }));
    proxy.links = graphData.links.map((data) => ({
        source : data.source ,
        target : data.target ,
        value : data.value
    }));
    return proxy;
}
```


Then pass the data like this


`<ForceGraph3D graphData={PropsDeepCopy(props.graphData.forceDirectedGraphData)} />`

**Comment by karanaryan07** [comment]
@Circles24 Thanks man for this solution, it worked and I checked and I found that ForceGraph3D was actually changing the give input object. 

@vasturiano thanks for your timely response and the floating point values were not an issue. I am closing this issue.
