### ISSUE TITLE
Move all graph canvas as a whole instead of rotating 3d

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#359]
**Is your feature request related to a problem? Please describe.**
I've searched for a way to make the rotation like the '2d' graph, where all the graph is like one image you can move, instead of rotating it. 

**Describe the solution you'd like**
A rotation mode / controlType which will make it possible. 

**Describe alternatives you've considered**
Right now I didn't found how to limit camera movement to only axes X and Y for that.
If you know any solution for my problem I'll be glad to know.

Thanks.

**Comment by vasturiano** [comment]
@nitzanorchestra if you right-click and drag you'll be able to pan the graph instead of rotating. That is a feature of [TrackballControls](https://threejs.org/docs/#examples/en/controls/TrackballControls).

**Comment by nitzanorchestra** [comment]
Thanks for the quick answer! Is there an option to toggle this panning in the left mouse click instead of rotating?

**Comment by RaulPROP** [comment]
Yes, you could change the [mouseButtons](https://threejs.org/docs/#examples/en/controls/TrackballControls.mouseButtons) object. (In the code it is initialized [like this](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/TrackballControls.js#L42), but you can override it).

**Comment by nitzanorchestra** [comment]
nice, in react-force-graph (3d)
I used:
```
const controls = this.graphRef.current.controls();
controls.mouseButtons.LEFT = this.props.isDimension2D ? 2 : 0;

```

But noticed that for it to work and not freeze the graph, I must also set the mouseButtons.RIGHT to the opposite values (if I put 2 in LEFT I also have to put 0 in RIGHT, can't keep it undefined because the graph freezes). Is that a bug that mouseButtons values has to be different?

**Comment by RaulPROP** [comment]
I don't see a reason for it to freeze.

[Here's the code of the mousedown funciton](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/TrackballControls.js#L440), it should work with undefined.

Have you tried another number greater than 3?

**Comment by nitzanorchestra** [comment]
No, i tried either the same number or undefined / null.
Try this in your codepen, you'll see you can't pan the graph no more:
 
```
controls.mouseButtons.LEFT = THREE.MOUSE.PAN;
controls.mouseButtons.RIGHT = undefined;
controls.mouseButtons.MIDDLE = undefined;
```

**Comment by RaulPROP** [comment]
Ok, i just realized the problem. First, let's see what is going on in the [mousedown function](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/TrackballControls.js#L440) (in the controller):

```js
switch ( event.button ) {

	case scope.mouseButtons.LEFT:
		_state = STATE.ROTATE;
		break;

	case scope.mouseButtons.MIDDLE:
		_state = STATE.ZOOM;
		break;

	case scope.mouseButtons.RIGHT:
		_state = STATE.PAN;
		break;

	default:
		_state = STATE.NONE;

}
```

Which means, whatever value is in the `mouseButtons.LEFT` will **ROTATE** the graph even tho we say MOUSE.PAN, and the same for the other buttons.

So, basically, we need to say which mouse button will rotate, pan and zoom and apply that value to mouseButtons.

e.g.:
To change rotation to right-click:
```js
graph.controller().mouseButtons.LEFT = THREE.MOUSE.RIGHT;
```

The previous codepen worked because MOUSE.PAN and MOUSE.RIGHT have the same values.

`var MOUSE = { LEFT: 0, MIDDLE: 1, RIGHT: 2, ROTATE: 0, DOLLY: 1, PAN: 2 };`.

I updated [the codepen](https://codepen.io/raulprop/pen/OJNXybB).

---

Just to be sure that I expressed myself clearly, just think of mouseButtons like this:

- mouseButtons.LEFT -> mouseButtons.TRANSLATE
- mouseButtons.MIDDLE -> mouseButtons.ZOOM
- mouseButtons.RIGHT -> mouseButtons.PAN

---

(@vasturiano) Maybe it would be a good idea to make some auxiliary functions to override these buttons like:


```js
function translateButton() {
    controller.mouseButtons.LEFT;
}

function translateButton(newValue) {
    controller.mouseButtons.LEFT = newValue;
}
```

**Comment by nitzanorchestra** [comment]
I read the code but I don't understand - isn't there a real separation between mouse button and action? So I can completely disable mouse button (let's say RIGHT button), or keep it the same while the LEFT button will also do panning

**Comment by RaulPROP** [comment]
> Like, let's say have panning both in RIGHT and LEFT, doesn't work.

No, it doesn't work, because **you don't assign the action to the mouse button, you assign the mouse button to the action**.

Basically, what you want is (in pseudo-code):
```
 controller.actionWhenLeftMouseButton = PAN;
 controller.actionWhenRightMouseButton = PAN;
```

but that can not be done (or at least I don't know how), what you can do is:

```
controller.whichButtonDoesThePanAction = MOUSE.LEFT;
```

which is the same as:

```
controller.mouseButton.RIGHT = THREE.MOUSE.LEFT;
```

But sadly, you can not assign an array to `controller.mouseButton.RIGHT`, like:

```
// pseudo-code
controller.whichButtonDoesThePanAction = THREE.MOUSE.LEFT and THREE.MOUSE.RIGHT; // This doesn't work
// javascript
controller.mouseButton.RIGHT = [THREE.MOUSE.LEFT, THREE.MOUSE.RIGHT] ; // This doesn't work
```

**Comment by nitzanorchestra** [comment]
No, I don't need an array, I just 
LEFT -> only pan
RIGHT -> undefined or keep it only pan.

is there an option for that?

**Comment by RaulPROP** [comment]
Yes, you can do:

```js
controller.mouseButtons.LEFT = undefined; // Disable rotation
controller.mouseButtons.RIGHT = THREE.MOUSE.LEFT; // or just 0, it sets the pan to the left mouse button.
```

**Comment by nitzanorchestra** [comment]
unfortunately your solution still disables panning for me: (graph "freezes")
controls.mouseButtons.LEFT = THREE.MOUSE.RIGHT;
controls.mouseButtons.RIGHT = undefined;

or even with this line commented
// controls.mouseButtons.RIGHT = undefined;

**Comment by RaulPROP** [comment]
Yes, that is misleading. Unfortunately, that's the [three.js](https://github.com/mrdoob/three.js) API, so it is not in this library's hands to change it.

Glad you achieved what you wanted, close the issue if everything is solved.

**Comment by nitzanorchestra** [comment]
yeah, thanks a lot guys!
