### ISSUE TITLE
Setting independent node/link styles

### ISSUE THREAD

**Issue by piaaaac** [vasturiano/3d-force-graph#37]
I'd like to set styles like opacity or link width based on my data.
I tried something like `Graph.nodeOpacity(d => d.opacity)` or `Graph.nodeOpacity("opacity")` but it's not working. 
Does anyone have a solution? thx

**Comment by vasturiano** [comment]
@piaaaac the syntax you're describing should work as long as each of your node objects has a `opacity` property with a numeric value between 0 and 1. 
To verify it, try replacing the argument with a constant, i.e. `.nodeOpacity(0.1)`.

**Comment by piaaaac** [comment]
For links: not sure what's wrong. Only explicit values work, when I pass a function of some kind the links disappear.
```
Graph.linkOpacity(0.5)                  // works
Graph.linkOpacity(d => 0.5)             // links brake
Graph.linkOpacity(() => 0.5)            // links brake
Graph.linkOpacity(() => Math.random(1)) // links brake
```

For nodes: solved. I'm using custom geometries so I act directly on the material with something like
```
Graph.nodeThreeObject(d => new THREE.Mesh(
  new THREE.SphereGeometry(3, 24, 18),
  new THREE.MeshBasicMaterial({
    color: d.color,
    transparent: true,
    opacity: d.opacity
  })
))
```

**Comment by vasturiano** [comment]
@piaaaac yes you are right. The opacity methods do not accept accessor functions but simply a constant value. This is mentioned in the docs. So, currently you can't set different opacities per node/link. 
This was the case because the objects are internally indexed per width and color (unless you're using custom node objects), for performance optimisation. And adding another dimension to this indexing would increase the cardinality and possibly affect the performance benefits.

For the nodes you can solve it by using the custom object functionality you referred to above. As for links, you can play with the link width per case, even going below 1px, which will give you similar results as different opacities, due to anti-aliasing.
