### ISSUE TITLE
How to toggle Bloom Layer on object onHover

### ISSUE THREAD

**Issue by szelenka** [vasturiano/3d-force-graph#390]
**Is your feature request related to a problem? Please describe.**
Similar to how the highlight example works, I'd like to be able to adjust the three.js object of those in the connection list. Such that when you hover over a node, it would apply a BloomPass on those objects.

This would be nearly identical to this example of selectively applying Bloom:
https://threejs.org/examples/?q=selective#webgl_postprocessing_unreal_bloom_selective
https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_unreal_bloom_selective.html

**Describe the solution you'd like**
From what I can tell (I'm still new to three.js), it seems the above example accomplished this through two EffectComposers. Where the `finalPass` is what will trigger the material change on the selected nodes based on the layer being enabled.

I can get the layers to toggle on the objects selected onHover, but after the layer is toggled, the Bloom effect s not rendered to the scene.

**Describe alternatives you've considered**
n/a

**Additional context**
Attempted to merge the two examples here, but I cannot figure out how to get the bloomComposer to trigger for the layers:
https://jsfiddle.net/025gnshu/1/

**Comment by szelenka** [comment]
I managed to get this to work ... the issue was importing the THREE libraries from //unpkg.com/ vs. //threejs.org/ .. seems there are some version issues there. Using directly from //threejs.org/ fixed the issue

**Comment by artt** [comment]
@szelenka Could you perhaps share a working version of the fiddle? I'm trying to do something similar but couldn't figure out how.

**Comment by szelenka** [comment]
It's been awhile, but I believe this was the trick:

`<script src="//unpkg.com/three@0.124"></script>`

For whatever reason, when using `//threejs.org/` it encountered the errors. I have not attempted to debug this since last September

**Comment by jdeb9** [comment]
Perchance I came across this issue while searching how to integrate the bloom example with `3d-force-graph` (though the react bindings `react-force-graph-3d`).

@artt Here's an updated version
https://codesandbox.io/s/threejs-bloom-sandbox-5u99z9?file=/src/index.js

@szelenka Did you end up finding a way to call `updateHighlight()` every time the force graph renders rather than just on node hover? The largest issue I've had with this library is the inaccessibility of not calling an `animate()` function myself.
