### ISSUE TITLE
Bug while dragging extended nodes

### ISSUE THREAD

**Issue by Ktulhu** [vasturiano/3d-force-graph#395]
I extend node with a text sprite. 

```javascript
        .nodeThreeObjectExtend(true)
        .nodeThreeObject(node => {
            const sprite = new SpriteText(`${node.id}`);
            sprite.color = 'white';
            sprite.textHeight = 3.5;
            sprite.position.y = 5;
            sprite.renderOrder = -1;
            return sprite;
        })
```

When you drag this text, it will break away from the node and crash 3d-force-graph

Simple demo to reproduce bug http://ktu.pw/v3dg.html

**Screenshots**

![](http://ktu.pw/v3dg_bug.png)

**Comment by MardariG** [comment]
Same for me. I understood [the hack with Sphere object](https://github.com/vasturiano/3d-force-graph/blob/master/example/text-nodes/index.html#L20-L24), but its a tricky one. If my text is bigger then sphere and I will try to drag from area out of Sphere zone, the issue is still there... maybe there is another solution?

**Comment by Ktulhu** [comment]
Thanks! Everything works correctly now
