### ISSUE TITLE
Graph content wobbles after moving a node to one of it's borders

### ISSUE THREAD

**Issue by nitzanorchestra** [vasturiano/3d-force-graph#413]
**Describe the bug**
Make a graph with defined height and width. 
When you drag one of it's nodes to the side, the graph wobbles like a rubber band. 

Generalization: same thing happens when mouse stop being down in the canvas context and instead intersect html content. 

You can see the problem here, but **resize the view so you can see the graph border**s. 
https://codepen.io/nitzanorchestra/pen/VwKLRBE

thanks!

**Comment by vasturiano** [comment]
Thanks for the report @nitzanorchestra!

This was happening because whenever the drag interaction goes off canvas it would trigger an end of drag and the camera controls would take over, thus causing a jump in the motion.

I've added an event to prevent the camera controls from taking over in this circumstance. Should be fixed in `v1.67.6`.
