### ISSUE TITLE
d3Force to modify link distance not working in Angular

### ISSUE THREAD

**Issue by AtomicNicos** [vasturiano/3d-force-graph#448]
**Describe the bug**
Using angular with library 3d-force-graph and trying to modify the link distance as per provided example: 

```
    const linkForce = graph
      .d3Force('link')
      .distance(link => link.color ? settings.redDistance : settings.greenDistance);
```

throws error of `Property 'distance' does not exist on type 'ForceFn'`.

**Expected behavior**
It should work like in the examples.

**Desktop (please complete the following information):**
 - OS: Win / Linux
 - Browser: Brave

**Comment by vasturiano** [comment]
@AtomicNicos is [this example](https://vasturiano.github.io/3d-force-graph/example/manipulate-link-force/) not working for you?

That follows the same pattern. If that is working for you, the issue is likely elsewhere in your app code, which is impossible to debug without more information. Could you please make a minimal [codepen](codepen.io) that reproduces your issue?

**Comment by RaulPROP** [comment]
I made a [small StackBlitz repo](https://stackblitz.com/edit/3d-force-graph-448?file=src/app/app.component.ts) to reproduce it and it is working fine.

**Comment by AtomicNicos** [comment]
@RaulPROP Your example doesn't work on local machines. (`An unhandled exception occurred: NGCC failed.`) 

I found that it is the internal TS Linter that errors out. If you add `// @ts-ignore` before the problematic lines, everything works fine.

So it is indeed not a package issue. Sorry for the inconvenience.
