### ISSUE TITLE
Node leaves graph layout when dynamically changing node size

### ISSUE THREAD

**Issue by evanzummeren** [vasturiano/3d-force-graph#455]
**Describe the bug**
I'm dynamically changing the node size of a THREE.SphereGeometry. However once I do this the node does increase in size, but it also leaves the graph layout.

**To Reproduce**
1. Change value of ```size``` key on existing object in nodes array from ```3``` to ```6```
2. Pass the entire data object to the ```graphData``` function.
3. The node size will increase, but it will pull away from the current graph force layout. (see screencap)

**Expected behavior**
I expect to increase the node size and to keep it part of the graph force layout.

**Screenshots**
![screencap](https://media0.giphy.com/media/qS1SMBzYMp1oFhFguJ/giphy.gif)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version 89

**Comment by vasturiano** [comment]
@evanzummeren thanks for reaching out.

It's difficult to say where the issue lies without more context. Could you make a simple example that reproduces the issue on [codepen](codepen.io)?

**Comment by evanzummeren** [comment]
Hi @vasturiano, thanks for getting back to this so quickly and for making such a cool component! I just uploaded the [code to codepen](https://codepen.io/evanzummeren/pen/abppVwy?editors=0010).

**Comment by vasturiano** [comment]
@evanzummeren I see what the issue is, you're actually replacing the whole node in your data structure, not just modifying one of its attributes. This means that the link connection to the node is lost, as the object reference no longer matches. This causes the node to break free, as you noticed.

So, the solution is to not create a new node, but instead modify it in place:
```js
nodeData[1].size = 6;
```

After that, you can simply tell the graph to refresh, and re-invoke your custom `nodeThreeObject` method, via:
```js
Graph.refresh();
```

**Comment by evanzummeren** [comment]
Amazing. Thank you so much @vasturiano!
