### ISSUE TITLE
Graph.cameraPosition in React

### ISSUE THREAD

**Issue by ellcyyang** [vasturiano/3d-force-graph#46]
Hello Mr. Vasturiano! I am using 3d-force-graph in a React app like in https://github.com/vasturiano/3d-force-graph/issues/10 , and I need to click to focus.
This is my code:
```
      <Graph 
        graphData={this.state.data}
          cameraPosition={[[this.state.poi],[this.state.target]]}
        linkWidth={l=>{
          if(l.emphasis){
            return 0.6;
          }
          return null;
        }}
        onNodeClick={node => {
            const count = 10;
            // Graph.cameraPosition({ x: node.x +100- count, y: node.y +100- count, z: node.z +100- count }, node);
            this.setState({poi: { x: node.x +100- count, y: node.y +100- count, z: node.z +100- count }, target: [node]});
          }}
      />
```
And the following error is displayed:
  ```
TypeError: Cannot set property 'target' of undefined
Function.cameraPosition
node_modules/3d-force-graph/dist/3d-force-graph.module.js:197
  194 |   if (y !== undefined) state.camera.position.y = y;
  195 |   if (z !== undefined) state.camera.position.z = z;
  196 | 
> 197 |   state.tbControls.target = lookAt ? new three.Vector3(lookAt.x, lookAt.y, lookAt.z) : state.forceGraph.position;
  198 | 
  199 |   return this;
  200 | }
```

Do you have any suggestions? 

Thank you! @vasturiano

**Comment by vasturiano** [comment]
@ellcyyang thanks for reaching out. The reason for the error is that the `cameraPosition` should not be called as a component prop, but as a method on the component itself, since it alters an internal state of the component. I'm adding a check protection to the component to prevent the error, but the interface should still be via a component method.

Also, I'd recommend using the [react-force-graph](https://github.com/vasturiano/react-force-graph) wrapper if you're using the lib with React. Particularly, this example seems to have the functionality you're seeking: https://vasturiano.github.io/react-force-graph/example/click-to-focus/
([source](https://github.com/vasturiano/react-force-graph/blob/master/example/click-to-focus/index.html))
