### ISSUE TITLE
Is there a suggested way to restart the graph after using stopAnimation?

### ISSUE THREAD

**Issue by cloudtracer** [vasturiano/3d-force-graph#47]
Based on the documentation it doesn't sound like it, but the thread regarding its original implementation it makes me think otherwise. Just thought I'd ask.

**Comment by vasturiano** [comment]
Hi @cloudtracer, currently the only way to restart the animation engine after it's been stopped with `stopAnimation()` is to re-initialize the graph which is triggered when you bind a DOM element to it. So, you can try re-binding the same DOM element via `myGraph(<domElement>)` to get the desired effect.

However, if what you're seeking is actually to temporarily stop the force engine instead of the animation cycle, you can do so with `cooldownTicks(0)`, and then re-ignite with `cooldownTicks(Infinity)`. This will keep the animation ticks running throughout.

Hope that helps.

**Comment by cloudtracer** [comment]
Cool thanks! Good tips. Re-binding is just want I needed.

It would be neat if you could wrap the functionality into stopAnimation so that it could be called with true/false. I've got what I need working, thanks again.
