### ISSUE TITLE
Optional cursor styling for background

### ISSUE THREAD

**Issue by S1r0hub** [vasturiano/3d-force-graph#476]
**Is your feature request related to a problem? Please describe.**
Using `onBackgroundClick` will assign the `clickable` class to the canvas [source](https://github.com/vasturiano/3d-force-graph/blob/981e46526505b6d2e49885c29fb454e43b258fd4/src/3d-force-graph.js#L387).
This class is usually removed for nodes and links when no longer hovering over them.
On the background however, it is always present and the cursor therefore always shows up as a pointer.
This makes it impossible to distinguish between interactions "hover node/link" and "hover background".

**Describe the solution you'd like**
I would like to see an option to disable this pointer (class) for the background, even if `onBackgroundClick` is set.

E.g. `showBackgroundPointer` with option `true / false`:
```javascript
// set pointer if hovered object is clickable
renderer.domElement.classList[
((hoverObj && state[`on${objType === 'node' ? 'Node' : 'Link'}Click`]) || (!hoverObj && state.onBackgroundClick && !state.showBackgroundPointer)) ? 'add' : 'remove'
]('clickable');
```

Note the `&& !state.showBackgroundPointer` part that I added to the [original code](https://github.com/vasturiano/3d-force-graph/blob/981e46526505b6d2e49885c29fb454e43b258fd4/src/3d-force-graph.js#L387) here.

Thanks.

**Comment by vasturiano** [comment]
@S1r0hub thanks for reaching out.

It is intentional to automatically set a pointer cursor for all parts of the canvas that have click actions associated to.
But if you don't wish to have the pointer styling applied, you can override the css from your application, for example like:
```css
.scene-container .clickable { 
  cursor: default !important;
}
```

You can also set this dynamically - or any other styling to signal an object is being hovered - using the `onNodeHover` and `onLinkHover` methods.

**Comment by S1r0hub** [comment]
@vasturiano Thanks for your reply.
I like the cursor styling and think its useful but I just don't want it for the background because then, one can not see a difference anymore when hovering over a node, over an edge or the background, as the cursor will always look the same.

The CSS snippet you provided turns off the pointer style for everything on the canvas (including nodes and links - what I don't want).
Once this is set, it is no longer possible to change the cursor to anything else using css as `!important` prevents it.

I don't know if this was what you meant but the following is working for me:
1. Add a new css rule for the cursor style which forces it to look as desired:
```css
.clickcursor {
    cursor: default !important;
}
```
2. Create a function to add and remove it from the class list of the canvas:
```javascript
function setClickCursor(object) {
    let canvas = graph.renderer().domElement;
    if (!object) { canvas.classList.add('clickcursor'); }
    else { canvas.classList.remove('clickcursor'); }
}
```
3. Call this method on node and link hover:
```javascript
graph.onNodeHover(node => setClickCursor(node));
graph.onLinkHover(link => setClickCursor(link));
```

I just thought that it could be a bit easier with the initial solution.
That's why I added this feature request.

**Comment by vasturiano** [comment]
@S1r0hub yes that's what I meant for dynamically setting the pointer style based on the hover event functions.

As to your original request, I understand the motivation but I think it's a bit of an edge case, and one that goes slightly against established UX principles for pointer cursors. In addition, it has the potential to snowball the API, because in the future another user will ask also for `showNodePointer` and `showLinkPointer`. Since there are ways of doing this with the existing `on*Hover` methods and for the above reasons I'm inclined to wait until there's more demand for this feature before adding it. Hope you understand.

**Comment by S1r0hub** [comment]
> As to your original request, I understand the motivation but I think it's a bit of an edge case, and one that goes slightly against established UX principles for pointer cursors. In addition, it has the potential to snowball the API, because in the future another user will ask also for `showNodePointer` and `showLinkPointer`. Since there are ways of doing this with the existing `on*Hover` methods and for the above reasons I'm inclined to wait until there's more demand for this feature before adding it. Hope you understand.

@vasturiano Yes, I understand and this is a valid argument against it.

> And just to be clear, the pointer on the background is only showing because you have defined `onBackgroundClick`. That should mean that you have some functionality behind the click interaction on the background. If the cursor doesn't reflect that, how will the user know it can click on the background?

In my case, I let the user clear a selection of nodes and links with a click on the background.
Therefore, it was not required to show the click functionality all the time.

At least there is now a post with a solution in case someone else needs this behaviour.
So I would close this issue now.

Thanks for your time and hints to solve it.
