### ISSUE TITLE
Allow the user to specific the scaling factor to use when determining initial camera z-axis dist

### ISSUE THREAD

**Issue by khughitt** [vasturiano/3d-force-graph#487]
**Problem**

Networks often appear smaller than desired.

**Possible solution**

From the notes for `cameraPosition`:

> By default the camera will face the center of the graph at a z distance proportional to the amount of nodes in the system.

Would it be possible to provide a mechanism to specific a scaling constant to be applied during this step? This way one could try tuning this to have the distance skew closer/farther away, as desired.

An alternate solution might be to provide something like `linkRelSize` that could be used to adjust the relative link lengths, while adjusting the node repulsion force proportionately to achieve the same relative link lengths. Then one could adjust by the relative node and link size to achieve a similar effect.

**Alternatives considered**

- I tried using `onEngineStop()` -> `zoomToFit()`, but it would be preferable to get the proportions right on the initially positioning and avoid any jumping around caused by successive camera movements.
- I think it should be possible use a combination of nodeRelSize, link distance, and force changes to get the desired effect, but thought I would suggest a simpler single parameter approach first in case it is something you think would be useful.

I'm not married to any of the above solutions. Just some thoughts on what might work well..

Overall though, the goal is just to provide a simple mechanism to control the relative scaling of the full network, at the time of loading.

Thanks a bunch!

Hope you are well.
Keith

**Comment by vasturiano** [comment]
@khughitt thanks for reaching out. 

You can already set your own custom distance from the nodes using the `cameraPosition` method. That is no different than exposing the factor to scale the distance based on the number of nodes set [here](https://github.com/vasturiano/3d-force-graph/blob/a0815ff8047030903c40b458f62cb7ee1da78618/src/3d-force-graph.js#L225).

F.e. like this:
```js
myGraph.cameraPosition({ z: Math.cbrt(numNodes) * 120 })
```
(note that it uses the cubic root of the node count because of the 3 dimensional space, but you can use a different logic if you prefer)

As for the links distance, if you'd like you can also manipulate that via the [forceLink distance method](https://github.com/vasturiano/d3-force-3d#link_distance).

**Comment by khughitt** [comment]
@vasturiano Great! I saw that the camera z-distance could be set, but I didn't realize how easy it would be to recreate your logic.

I appreciate you taking the time to respond.

I've been been using 3d-force-graph more-and-more recently, and have thoroughly enjoyed it. I'm hoping to have the time in the coming months to become more familiar with the codebase and see if I can actually start contributing back. May take longer, but I will get there.. 

Thanks again! Going to close as a _non-issue_.
