### ISSUE TITLE
Add floor texture to scene

### ISSUE THREAD

**Issue by Piyush3dB** [vasturiano/3d-force-graph#55]
Hello @vasturiano ,

First of all thanks for the fantastic library!

I have a requirement where I'd like a "floor" to appear beneath my 3D force graph - essentially a plane geometry with image texture.  Is there a function I can call on the ForceGraph3D object to achieve this?

Best Regards,
@Piyush3dB

**Comment by vasturiano** [comment]
Hi @Piyush3dB, thanks for reaching out. From the latest version (`1.30.0`) there is a new method exposed: `scene()`. You can use that method to access the ThreeJS scene and extend it with other objects like the "floor" that you mentioned.
Something along the lines of:
```
myGraph.scene().add(<Object3d>)
```

**Comment by artyomtrityak** [comment]
@Piyush3dB here is an example https://github.com/vasturiano/3d-force-graph/pull/66

**Comment by Piyush3dB** [comment]
<img width="836" alt="screen shot 2018-05-02 at 07 07 47" src="https://user-images.githubusercontent.com/8223608/39507812-a40b0cf8-4dd7-11e8-801f-15cd6df733e9.png">

@artyomtrityak, thanks for the example.  I ran the [example](https://raw.githubusercontent.com/artyomtrityak/3d-force-graph/5190dff07e59a9b24d8da42ff5a10da323cb3b0f/example/scene/index.html) locally and what I see during the rendering is a red plane initially which immediately changes to a red node and stays that way.

Is this what you also got?

**Comment by vasturiano** [comment]
The underlying issue was that` three.js` was being loaded *after* `3d-force-graph` (it includes its own `three` if there is none readily available at import time). That will lead into there being two parallel copies of `three.js` running in the page, which leads to the interference you mentioned above. I've fixed the example to load `three.js` *before* `3d-force-graph`, and it's fixed:
https://vasturiano.github.io/3d-force-graph/example/scene/

**Comment by Piyush3dB** [comment]
Thanks @vasturiano that works great now.
