### ISSUE TITLE
How to display additional info about a link/node ?

### ISSUE THREAD

**Issue by bnzone** [vasturiano/3d-force-graph#593]
Hi there! 👋🏻

First of all, thank you very much for this nice library! 

I'm trying to display some information when user clicks on a `link` or a `node`.

I saw there's `onLinkClick` and `onNodeClick` methods, but how would you suggest displaying some box or `HTML` with some additional data next to that link or node when user clicks them?

Here's what I have in mind when user clicks on the link between the `node A` and `node B` and sees some info about the connection. A similar box I'm imagining when user clicks on a node.
Thank you in advance for any suggestions 🙏🏻
![Screen Shot 2023-01-10 at 10 31 21 AM](https://user-images.githubusercontent.com/39371503/211608165-87a32c12-ed2f-444c-8b59-6196816e17c9.png)

**Comment by vasturiano** [comment]
@bnzone if you want to do it on hover interaction, you already have the tooltip functionality done for you via `nodeLabel` or `linkLabel`.

Otherwise, each of the `onNodeClick` or `onLinkClick` include the click event as second argument in the callback. You can use this event object to extract the click coordinates, and overlay your own custom div in position on top of the graph canvas element.

**Comment by bnzone** [comment]
@vasturiano Thank for you the quick response! 
I will see if the hover will suffice otherwise I'll take your advice and implement custom overlay.
Thanks again!

**Comment by mittelmanjournal** [comment]
How would I make the content of linkLabel only visible on click instead of the default which makes it visible on hover. I was thinking about making the linkLabel html not visible (Graph.linkLabel(link => "<div \"style: visibility: hidden\"> content</div>") and then Graph.onLinkClick(link => link.linkLabel().visibility = "visible"). But this doesn't work.
