### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by gitgitwhat** [vasturiano/3d-force-graph#63]
Could you expose ondblclick?  It'd be really nice to have that callback available.  

Not that you need it but I found this fiddle that shows the double click hit testing.

http://jsfiddle.net/ddbTy/241/

Thanks.

**Comment by gitgitwhat** [comment]
That's fair.  Like you said it's not a normal browser action.  I ended up just combing the double click action (showing a popup) with the single click (zooming to node) which in my use case works well.

**Comment by irosen419** [comment]
Hello @vasturiano ! So I am also looking into using the double click action for a graph node for this reason....

My graph works great on desktop, and can be seen here (newvisionresearch.org/impact). However, on mobile, it is incredibly sensitive, so when I try to zoom using two finger, if I accidentally click a node, it will zoom in on the node. Right now, I was thinking of adding a double-click action to the nodes for mobile. Do you have any other suggestions?

**Comment by vasturiano** [comment]
@irosen419 thanks for reaching out.
I've just pushed an update that makes the accidental triggers on touch screens less likely to happen, so you can check if that solves your issue.
Regardless, yes you should be able to add double-click events to the nodes easily. You should be able to derive it from the `onNodeClick` method.

**Comment by irosen419** [comment]
@vasturiano thanks so much! I will keep working on it!

**Comment by SquabbyZ** [comment]
You can use Raycaster @irosen419

**Comment by anyuruf** [comment]
Found this of implementing a double click from a  one but have not tested it yet
Latest Solution:

Instead of utilizing more ad-hoc states and setTimeout, turns out there is a native property called detail that you can access from the event object! Modern browsers and even IE-9 supports it :) [Source](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail)

element.onclick = event => {
   if (event.detail === 1) {
     // it was a single click
   } else if (event.detail === 2) {
     // it was a double click
   }
};
from https://javascript360.org/blog/double-click-polyfill/
