### ISSUE TITLE
Latest release seems to elicit new warning in browser console

### ISSUE THREAD

**Issue by emirth** [vasturiano/3d-force-graph#638]
**Describe the bug**

Recent versions seem to introduce a warning in the browser console.

**To Reproduce**
1. Go to [the example running 1.71.0](https://jsfiddle.net/emirth/rqwg7jb0/1/)
2. Click on '▷ **Run**'
3. Open the browser developer console
4. Note lack of error:
![image](https://github.com/vasturiano/3d-force-graph/assets/85695145/1ee9b3aa-c6ef-4cae-a095-54da9eba2488)
5. Go to [the example running latest](https://jsfiddle.net/emirth/he7nvx90/)
6. Click on  '▷ **Run**'
7. Open the browser developer console
8. Note the new error from `THREE.WebGLRenderer`: 
![image](https://github.com/vasturiano/3d-force-graph/assets/85695145/8253f1a8-2b64-4b41-9fec-e12438543143)

**Expected behavior**
Running latest, no warning from `THREE.WebGLRenderer` would surface in developer console.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 116 64 bit

**Smartphone (please complete the following information):**
*not applicable*

**Additional context**
*not applicable*

**Comment by vasturiano** [comment]
Thanks @emirth for reaching out and for your report.

I know about this warning, and is unavoidable unfortunately. The main reason is that in order to support multiple ThreeJS versions, before and after r155, we need to force this flag to the new behaviour `useLegacyLights=false`. Which in turn leads to this warning by ThreeJS internally.

There's more back story info on this feature compatibility here: https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733
