### ISSUE TITLE
How to use StereoCamera in renderControl?

### ISSUE THREAD

**Issue by PixDay** [vasturiano/3d-force-graph#642]
Hi I would like to make my graph working with 3D goggles in stereoscopic mode, is there any possibility to do that ?

It is possible to change the camera set in the renderControl to use a [stereoCamera](https://threejs.org/docs/#api/en/cameras/StereoCamera) ?

**Comment by vasturiano** [comment]
@PixDay thanks for reaching out.

For that type of setup I would suggest to consume from the lower-level [three-force-graph](https://github.com/vasturiano/three-forcegraph). That gives you full freedom to setup your camera/scene/renderer the way you prefer, including making the camera a stereo camera instead of perspective.

**Comment by PixDay** [comment]
I don't see how or where I can change the camera that is set by default in the `ForceGraph3D` is it what you are refering too?

**Comment by vasturiano** [comment]
I'm referring to using the [three-force-graph](https://github.com/vasturiano/three-forcegraph) module instead of this one [3d-force-graph](https://github.com/vasturiano/3d-force-graph).

**Comment by PixDay** [comment]
I see, it wont work easily for me and my project, I'm using a lot of feature present in the 3d-force-graph, if you have any other idea on how to make that work otherwise I will just close this issue.

Thanks for the help

**Comment by vasturiano** [comment]
@PixDay what's an example of a feature that you need from `3d-force-graph`?

Swapping the perspective camera with a stereo camera is not as easy as just instantiating a different camera class, because things like TrackballControls don't really work out of the box when using a different camera type. That's why for these cases it's better to craft your own custom ThreeJS scaffolding so that you can customize it to your needs. I can't see another way to do it.

**Comment by PixDay** [comment]
It's possible to have 2 cameras on one graph scene? So I can play with angles to create my effect

**Comment by vasturiano** [comment]
All of those options are possible if you setup your own scene and use `three-force-graph`.

**Comment by PixDay** [comment]
It's not possible to add a second camera in ForceGraph3d ?

**Comment by vasturiano** [comment]
Not as it stands currently, no. The setup in `3d-force-graph` is intended as the most common use case of the ThreeJS scene/camera scaffolding, so that the consumer doesn't have to do it repeatedly. Having more than one camera is not really part of this common case, and for these custom cases the most flexible approach is to manage your own scaffolding.

**Comment by PixDay** [comment]
I had an idea that worked for me, is to create a THREE scene, and add referenced threeObject inside the scene to keep it sync and then add 2 cameras so it's working

Thanks for the help
