### ISSUE TITLE
CameraPosition promise

### ISSUE THREAD

**Issue by rkalidhindi-tanium** [vasturiano/3d-force-graph#97]
Hi @vasturiano 

I am using `cameraPosition` with a delay time, and I was wondering if it returned a promise, callback, or anything like that that would allow me to run certain commands immediately after it finishes the moving.  Currently I set a timeout after calling the cameraPosition method and use that to execute the commands.

Thank you for the amazing library and constant support!

**Comment by vasturiano** [comment]
@rkalidhindi-tanium yeah, I think the `setTimeout` approach works fine since the transition is time based anyway. 
Returning a promise would unfortunately break the current interface which is to return the instance itself for easy method chaining. A callback could be added as a (4th) parameter, but that may over complicate the method signature.
Since there's an easy workaround with a timeout, I'm inclined to leave the interface as is until it proves problematic in some way.

And thanks for all your feedback! That's how we improve the library! 🎉

**Comment by rkalidhindi-tanium** [comment]
Thank you for the explanation, that makes a lot of sense :)
